### ISSUE TITLE
Implement a ui

### ISSUE THREAD

**Issue by DomiiBunn** [kinshukdua/LiveActionMap#1]
I think it would be a pretty good idea to implement a ui for this instead of just generating a PNG. 

If needed i could spare some time in Vue. By all means i have a free weekend right now.

**Comment by kinshukdua** [comment]
Hi, this doesn't generate a png but an html interactive map.

I've set up a server to automatically generate the map and host it.

You can find it here:

http://18.191.203.165/

Until I get a domain.

**Comment by tesla-srt** [comment]
I also have some free time and would love to contribute :)

**Comment by DomiiBunn** [comment]
Oh. Sorry i didn't look into the code before posting. So yeah i guess it's closed

**Comment by kinshukdua** [comment]
> I also have some free time and would love to contribute :)

@tesla-srt That would be great! I've listed out some things you can do in the rooadmap but please feel free to contribute in any way by making a pull request.
