### ISSUE TITLE
Cache Nominatim geocoding API

### ISSUE THREAD

**Issue by laurin** [kinshukdua/LiveActionMap#13]
As getting the latitude and longitude of the found location seems to be the most time-consuming operation, it would  probably make sense to cache the responses of the Nominatim API.

**Comment by kinshukdua** [comment]
You're right, the quickest solution is to create a function that just calls the Nominatim API and wrap it with @cache but this would only work for a single execution of the script. The second way is to store the lat and long of the city into a database and update that accordingly and I think this is probably the best solution.
