### ISSUE TITLE
Add CI/CD and Tests

### ISSUE THREAD

**Issue by kinshukdua** [kinshukdua/LiveActionMap#22]
As the project grows, we need a way to make sure it is easy to test incoming PRs instead of me manually pulling and testing everything. The best way would be to setup a CI/CD pipeline using Github Actions. At the present moment we don't have any tests except the one introduced in #21. Ideally I would like to setup tests and then a CI/CD pipeline. However, the server running the website right now, is manually using cron jobs. I would instead like to wait for #16 to finish and then create a pipeline with the docker image.

Meanwhile, feel free to add tests and help me write a CI pipeline.

**Comment by GabrieleCalarota** [comment]
I'm glad to help writing a CI workflow for github actions and help for the deploy pipeline

**Comment by kinshukdua** [comment]
@GabrieleCalarota thanks for offering to help! With the docker container finally set up, we can finally start integrating a CI workflow.

**Comment by GabrieleCalarota** [comment]
I'm writing a CI pipeline in this PR on my forked repo 

https://github.com/GabrieleCalarota/LiveActionMap/pull/2

It will need a lot of rework, as the project is not born along with linting

**Comment by DomiiBunn** [comment]
As I see that the PR is merged is this Issue still valid or to be closed?

**Comment by kinshukdua** [comment]
It's still valid because CD pipeline and tests still need to be implemented.

**Comment by DomiiBunn** [comment]
Ah, Sorry.

**Comment by DomiiBunn** [comment]
Hey, So sadly I never worked with GitHub CI. However is there a chance to have a simple webhook trigger to have it auto-deploy on my docker host? @GabrieleCalarota Can you hop in discord so we can discuss the details?

**Comment by GabrieleCalarota** [comment]
> Hey, So sadly I never worked with GitHub CI. However is there a chance to have a simple webhook trigger to have it auto-deploy on my docker host? @GabrieleCalarota Can you hop in discord so we can discuss the details?

Sure, why don't we use GitHub discussions?

**Comment by DomiiBunn** [comment]
They're not enabled here. And personally, at least discord feels more... I think easy would be a suitable word?

**Comment by DomiiBunn** [comment]
If there is a chance to add
```
curl -X POST \
     --fail \
     -F token=GITLAB_TOKEN \
     -F ref=GITLAB_REF_NAME \
     https://gitlab.com/api/v4/projects/34155787/trigger/pipeline
```
to the CI after all tests are complete?

**Comment by GabrieleCalarota** [comment]
> If there is a chance to add
> 
> ```
> curl -X POST \
>      --fail \
>      -F token=GITLAB_TOKEN \
>      -F ref=GITLAB_REF_NAME \
>      https://gitlab.com/api/v4/projects/34155787/trigger/pipeline
> ```
> 
> to the CI after all tests are complete?

Yes, there should be a way or an action for doing normal POST or webhook triggers. But why don't we move the CD pipeline to github instead of having the deployment somewhere else where from the code?


Also is that the official deployment of the repo? @kinshukdua

**Comment by GabrieleCalarota** [comment]
Ok fine, sorry didn't have time to download it yet

Anyway: https://github.com/marketplace/actions/trigger-gitlab-ci

I think this action would do the trick, will you set GITLAB_TOKEN and GITLAB_REF_NAME as repo secret?
For best practice, I would add also GITHUB_URL and PROJECT_ID as secrets

the code at the end would be :

```
- name: trigger Job
  uses: appleboy/gitlab-ci-action@master
  with:
    url: ${{ secrets.GITLAB_URL }}
    token: ${{ secrets.TOKEN }}
    project_id: ${{ secrets.PROJECT_ID }}
    ref: ${{ secrets.GITLAB_REF_NAME }}
```

**Comment by DomiiBunn** [comment]
Url doesn't need to be secret it's just `https://gitlab.com` and project id is `34155787` but yeah @kinshukdua can you fill thoe out?

**Comment by DomiiBunn** [comment]
If you could take a look @GabrieleCalarota since I don't know how to make it run only after merge. Atm, it seems to run on merge requests as well,
And erm, It seams to have failed
