### ISSUE TITLE
Dynamic Fronted

### ISSUE THREAD

**Issue by DomiiBunn** [kinshukdua/LiveActionMap#25]
How about I make a quick mockup with vuejs that would just read an api. That way once the project is evolved enough it would be enough to just hook one and the other together.

_Originally posted by @Krishna-Sivakumar in https://github.com/kinshukdua/LiveActionMap/issues/24#issuecomment-1053660218_

**Comment by kinshukdua** [comment]
Yes, sounds good that way we can easily move to  a more traditional dynamic frontend and backend system when the project gets complex enough.

**Comment by DomiiBunn** [comment]
I'll start on this tonight ^.^

**Comment by DomiiBunn** [comment]
For now, I started a separate repo not to clutter up the main one with UI files

https://gitlab.com/DomiiBunn/live-action-map-ui
