### ISSUE TITLE
IP Blocking - Russia?

### ISSUE THREAD

**Issue by DomiiBunn** [kinshukdua/LiveActionMap#28]
Should we block Russia from using the applet?

This might be actually helpful in order not to leak possible troop information,

**Comment by kinshukdua** [comment]
People can always straight up use twitter or download the repo from GitHub to create their own map, that defeats the purpose of blocking Russian IPs.

**Comment by DomiiBunn** [comment]
True true

**Comment by sahal-mulki** [comment]
But let's at least try, eh?

**Comment by DomiiBunn** [comment]
IDK, for me, it's just one click. I'm not making the decision tho.

**Comment by sahal-mulki** [comment]
ok, how should we implement this ip filter?

**Comment by DomiiBunn** [comment]
I can just block it on the domain level. As the domain runs on it it's a simple firewall rule

**Comment by sahal-mulki** [comment]
your hosting it?
ok good idea.

**Comment by sahal-mulki** [comment]
can you add me as a collaborator too?

**Comment by DomiiBunn** [comment]
> your hosting it? ok good idea.

I'm just proxying it and have the domain pointed at it. It's hosted by @kinshukdua atm.

**Comment by sahal-mulki** [comment]
can you add me as a collaborator too?

**Comment by sahal-mulki** [comment]
please.

**Comment by laurin** [comment]
I think we can just close the issue, this does not make sense.

**Comment by sahal-mulki** [comment]
ok @DomiiBunn

**Comment by kinshukdua** [comment]
Yeah, we should close this issue. We can reopen this if we get any significant attacks coming from Russian IPs.
