### ISSUE TITLE
Feature Suggestion: Plane Tracking 

### ISSUE THREAD

**Issue by DomiiBunn** [kinshukdua/LiveActionMap#31]
Add selective plane Tracking to the map
Useful api
https://opensky-network.org/

**Comment by sahal-mulki** [comment]
No sensible russian pilots would turn on transponders while in ukranian airspace ಠ_ಠ

**Comment by kinshukdua** [comment]
Warplanes don't show up in networks like these because they depend on public data to ATC, so I am not sure if this would be useful or if it would help unnecessarily clutter the map. Just to cross check I want through the website and saw zero planes flying over Ukraine.

**Comment by DomiiBunn** [comment]
I'm thinking more about the future. 

This does seem like a neat project to keep alive after the conflict gets resolved. I'd add watchers for tsunamis and other similar catastrophies?

**Comment by sahal-mulki** [comment]
@kinshukdua is right, sorry.

**Comment by DomiiBunn** [comment]
Yeah for the current moment I agree ^.^

**Comment by sahal-mulki** [comment]
Can I be added as collaborator, please?
@kinshukdua
