### ISSUE TITLE
add website domain in repo website

### ISSUE THREAD

**Issue by Alirezaaraby** [kinshukdua/LiveActionMap#36]

**Comment by DomiiBunn** [comment]
Can you please elaborate?

**Comment by andreAbtahi96** [comment]
I am confused. Could you explain @Alirezaaraby

**Comment by Krishna-Sivakumar** [comment]
The website link can be added in the description, I think that's what they mean.

**Comment by andreAbtahi96** [comment]
I thought it is already in the description @Krishna-Sivakumar

**Comment by Krishna-Sivakumar** [comment]
@Alirezaaraby you can add a website link on the right-hand-side tab, by clicking the gear icon

**Comment by Alirezaaraby** [comment]
![IMG_20220301_120124.jpg](https://user-images.githubusercontent.com/45128978/156133414-c5e643b2-51fc-4b0e-a550-1e714a9afc95.jpg)
 You can add repository website from here and then in the opened modal you can see 

![IMG_20220301_120337.jpg](https://user-images.githubusercontent.com/45128978/156133638-87ddc820-549d-4267-a0ba-05397a304926.jpg)
 Website

**Comment by kinshukdua** [comment]
@Alirezaaraby Added the website in the about section, thank you for your suggestion.
