### ISSUE TITLE
Remove temporary tweets file after every x minutes.

### ISSUE THREAD

**Issue by kinshukdua** [kinshukdua/LiveActionMap#48]
Since we're no longer dependent on the cronjob, we need to remove the tweets in the python code itself. However deleting the file after each run as done in an earlier PR is not useful because there's too few data points, we can try to increase the number of results we get from Twitter but that's a separate issue.

Also let's make sure the schedule time for the scraping and removing tweets don't overlap (they are not multiples) otherwise the tweets file might be deleted while the bot is running outputting an empty map.

**Comment by Krishna-Sivakumar** [comment]
I think this can be closed now @kinshukdua
