### ISSUE TITLE
Add blacklist 

### ISSUE THREAD

**Issue by kinshukdua** [kinshukdua/LiveActionMap#5]
Add a blacklist for Twitter accounts spreading misinformation.

**Comment by GabrieleCalarota** [comment]
I'm working on a pullrequest at https://github.com/GabrieleCalarota/LiveActionMap , will submit it by the end of today

**Comment by sahal-mulki** [comment]
Will the blacklist be manually updated?

**Comment by GabrieleCalarota** [comment]
It depends as of the moment I'm adding it as an environment variable and it can be pre-filled in .env.example, it could be on a shared file hosted

**Comment by sahal-mulki** [comment]
So it's manually filled in, opposing automaticcaly using nlp?

**Comment by GabrieleCalarota** [comment]
> So it's manually filled in, opposing automaticcaly using nlp?

Yep, that could be the roadmap
