### ISSUE TITLE
Dockerize for Scalability

### ISSUE THREAD

**Issue by DomiiBunn** [kinshukdua/LiveActionMap#7]
I don't really know a lot about python but should dockerize the app for easier future scalability.

**Comment by DomiiBunn** [comment]
Also also. Would you have a way to communicate more live? I'd say discord?

**Comment by DomiiBunn** [comment]
As I'm looking at the code. It generates an index.html
I haven't ever really touched python but would it be possible for it instead of generating the file to host the data live? Maybe run a scrape every 5-10 mins and host the file? This would make the app more scalable. Even better would be if the backed was to save the data to a DB and then have a middleware serving the actual map data. But that might be a little over the top...

**Comment by kinshukdua** [comment]
@DomiiBunn yes, my discord is superboyk#5755
I agree with your suggestion to dockerize, however I have limited experience with docker.
Currently I'm doing the following to host the files. I'm using a simple apache server to host the static html file.

1. Create a shell script to a) add environment variable, b) run `scrape.py` to create an `index.html` file, c) move `index.html` to `/var/www/html` 
2. Setup a cron job to call the script every 10 minutes

**Comment by laurin** [comment]
I' currently working on containerizing this.
I think it would be best if we can merge #12, so the generated file can be mounted easily

**Comment by kinshukdua** [comment]
@laurin there is a merge conflict in #12, I need to resolve that I'll merge after that.
